package com.example.demo.entity;

public class consigneeManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee_management.consignee_id
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    private Integer consigneeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee_management.user_id
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee_management.consignee_name
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    private String consigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee_management.consignee_address
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    private String consigneeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee_management.consignee_code
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    private String consigneeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consignee_management.consignee_phone
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    private String consigneePhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee_management.consignee_id
     *
     * @return the value of consignee_management.consignee_id
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public Integer getConsigneeId() {
        return consigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee_management.consignee_id
     *
     * @param consigneeId the value for consignee_management.consignee_id
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public void setConsigneeId(Integer consigneeId) {
        this.consigneeId = consigneeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee_management.user_id
     *
     * @return the value of consignee_management.user_id
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee_management.user_id
     *
     * @param userId the value for consignee_management.user_id
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee_management.consignee_name
     *
     * @return the value of consignee_management.consignee_name
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee_management.consignee_name
     *
     * @param consigneeName the value for consignee_management.consignee_name
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName == null ? null : consigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee_management.consignee_address
     *
     * @return the value of consignee_management.consignee_address
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee_management.consignee_address
     *
     * @param consigneeAddress the value for consignee_management.consignee_address
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress == null ? null : consigneeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee_management.consignee_code
     *
     * @return the value of consignee_management.consignee_code
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public String getConsigneeCode() {
        return consigneeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee_management.consignee_code
     *
     * @param consigneeCode the value for consignee_management.consignee_code
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public void setConsigneeCode(String consigneeCode) {
        this.consigneeCode = consigneeCode == null ? null : consigneeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consignee_management.consignee_phone
     *
     * @return the value of consignee_management.consignee_phone
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consignee_management.consignee_phone
     *
     * @param consigneePhone the value for consignee_management.consignee_phone
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }
}