package com.example.demo.entity;

public class GoodsImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_img.img_id
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_img.goods_id
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_img.img_url
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_img.img_id
     *
     * @return the value of goods_img.img_id
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_img.img_id
     *
     * @param imgId the value for goods_img.img_id
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_img.goods_id
     *
     * @return the value of goods_img.goods_id
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_img.goods_id
     *
     * @param goodsId the value for goods_img.goods_id
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_img.img_url
     *
     * @return the value of goods_img.img_url
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_img.img_url
     *
     * @param imgUrl the value for goods_img.img_url
     *
     * @mbggenerated Tue Jun 26 23:48:45 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}