package com.example.demo.entity;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_id
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_name
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_price
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_url
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private String goodsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_desc
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private String goodsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_state
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private String goodsState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.user_id
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_position
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private String goodsPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_info.goods_num
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    private Integer goodsNum;


    private String userContact;
    private String goodsEndate;
    private String goodsStartdate;
    private String goodsTitle;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_id
     *
     * @return the value of goods_info.goods_id
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_id
     *
     * @param goodsId the value for goods_info.goods_id
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_name
     *
     * @return the value of goods_info.goods_name
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_name
     *
     * @param goodsName the value for goods_info.goods_name
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_price
     *
     * @return the value of goods_info.goods_price
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_price
     *
     * @param goodsPrice the value for goods_info.goods_price
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_url
     *
     * @return the value of goods_info.goods_url
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public String getGoodsUrl() {
        return goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_url
     *
     * @param goodsUrl the value for goods_info.goods_url
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl == null ? null : goodsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_desc
     *
     * @return the value of goods_info.goods_desc
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_desc
     *
     * @param goodsDesc the value for goods_info.goods_desc
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_state
     *
     * @return the value of goods_info.goods_state
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public String getGoodsState() {
        return goodsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_state
     *
     * @param goodsState the value for goods_info.goods_state
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsState(String goodsState) {
        this.goodsState = goodsState == null ? null : goodsState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.user_id
     *
     * @return the value of goods_info.user_id
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.user_id
     *
     * @param userId the value for goods_info.user_id
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_position
     *
     * @return the value of goods_info.goods_position
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public String getGoodsPosition() {
        return goodsPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_position
     *
     * @param goodsPosition the value for goods_info.goods_position
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsPosition(String goodsPosition) {
        this.goodsPosition = goodsPosition == null ? null : goodsPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_info.goods_num
     *
     * @return the value of goods_info.goods_num
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_info.goods_num
     *
     * @param goodsNum the value for goods_info.goods_num
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    public String getUserContact() {
        return userContact;
    }

    public void setUserContact(String userContact) {
        this.userContact = userContact == null ? null : userContact.trim();
    }

    public String getGoodsEndate() {
        return goodsEndate;
    }

    public void setGoodsEndate(String goodsEndate) {
        this.goodsEndate = goodsEndate == null ? null : goodsEndate.trim();
    }

    public String getGoodsStartdate() {
        return goodsStartdate;
    }

    public void setGoodsStartdate(String goodsStartdate) {
        this.goodsStartdate = goodsStartdate == null ? null : goodsStartdate.trim();
    }

    public String getGoodsTitle() {
        return goodsTitle;
    }

    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle == null ? null : goodsTitle.trim();
    }
}