package com.example.demo.entity;


public class ShopCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.car_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private String carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.user_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.goods_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.goods_img
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private String goodsImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.goods_name
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.goods_price
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.goods_num
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private Integer goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.total_price
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private Double totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_car.state
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.car_id
     *
     * @return the value of shop_car.car_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.car_id
     *
     * @param carId the value for shop_car.car_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.user_id
     *
     * @return the value of shop_car.user_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.user_id
     *
     * @param userId the value for shop_car.user_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.goods_id
     *
     * @return the value of shop_car.goods_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.goods_id
     *
     * @param goodsId the value for shop_car.goods_id
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.goods_img
     *
     * @return the value of shop_car.goods_img
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.goods_img
     *
     * @param goodsImg the value for shop_car.goods_img
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.goods_name
     *
     * @return the value of shop_car.goods_name
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.goods_name
     *
     * @param goodsName the value for shop_car.goods_name
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.goods_price
     *
     * @return the value of shop_car.goods_price
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.goods_price
     *
     * @param goodsPrice the value for shop_car.goods_price
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.goods_num
     *
     * @return the value of shop_car.goods_num
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.goods_num
     *
     * @param goodsNum the value for shop_car.goods_num
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.total_price
     *
     * @return the value of shop_car.total_price
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.total_price
     *
     * @param totalPrice the value for shop_car.total_price
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_car.state
     *
     * @return the value of shop_car.state
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_car.state
     *
     * @param state the value for shop_car.state
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}