package com.example.demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.example.demo.entity.consigneeManage;

public interface consigneeManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int countByExample(consigneeManage example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int deleteByExample(consigneeManage example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int deleteByPrimaryKey(Integer consigneeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int insert(consigneeManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int insertSelective(consigneeManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    List<consigneeManage> selectByExample(consigneeManage example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    consigneeManage selectByPrimaryKey(Integer consigneeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") consigneeManage record, @Param("example") consigneeManage example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int updateByExample(@Param("record") consigneeManage record, @Param("example") consigneeManage example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int updateByPrimaryKeySelective(consigneeManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consignee_management
     *
     * @mbggenerated Tue Jun 26 21:21:18 CST 2018
     */
    int updateByPrimaryKey(consigneeManage record);
}