package com.example.demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.example.demo.entity.Goods;


public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int countByExample(Goods example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int deleteByExample(Goods example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int insert(Goods record);

    int insertGoods(Goods good);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    List<Goods> selectByExample(Goods example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    Goods selectByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") Goods example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int updateByExample(@Param("record") Goods record, @Param("example") Goods example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_info
     *
     * @mbggenerated Tue Jun 26 22:58:57 CST 2018
     */
    int updateByPrimaryKey(Goods record);
}