package com.example.demo.dao;



import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.example.demo.entity.ShopCar;


public interface ShopCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int countByExample(ShopCar example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int deleteByExample(ShopCar example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int deleteByPrimaryKey(String carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int insert(ShopCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int insertSelective(ShopCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    List<ShopCar> selectByExample(ShopCar example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    ShopCar selectByPrimaryKey(String carId);

    ShopCar getShopCarById(String goodId,int userId);

    int insertGoods(ShopCar good);

    int updataGoods(ShopCar good);

    int handleOnShelf(String good);

    int handleOffShelf(String good);

    int updataGoodsInfo(ShopCar good);

    List<ShopCar> queryCarGoodsByUser(int userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") ShopCar record, @Param("example") ShopCar example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int updateByExample(@Param("record") ShopCar record, @Param("example") ShopCar example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int updateByPrimaryKeySelective(ShopCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_car
     *
     * @mbggenerated Tue Jul 17 22:47:52 CST 2018
     */
    int updateByPrimaryKey(ShopCar record);
}
